export default {
	ERR_UNSUPPORTED_TYPE: "UNSUPPORTED TYPE, IPNS AND IPFS REFS ONLY",
	ERR_RESOLVE_CONFLICT: "FAILED TO RESOLVE",
	ERR_404_NOT_FOUND: "404 NOT FOUND",
	ERR_NO_STATIC_CONTENT: "NO STATIC CONTENT AVAILABLE",
	ERR_NO_ONION_SERVICE: "NO ONION SERVICE AVAILABLE",
	ERR_REVERSE_ONION: "REVERSE ONION RESOLUTION FAILURE",
	ERR_FAILED_FETCH: "FAILED TO FETCH IPFS CONTENT",
	SERVER_INIT: "// RESOLVER ::: ON //",
	SERVER_FAIL: "// FAILURE ::: OFF //"
}